# Generated by Django 4.2.2 on 2023-06-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_cars_is_favorite_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
