# Generated by Django 4.2.2 on 2023-06-21 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rename_is_favorite_cars_is_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='is_favorites',
        ),
    ]
