# Generated by Django 4.2.2 on 2023-06-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_cars_is_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
