# Generated by Django 4.2.2 on 2023-06-22 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_cars_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='cost',
            field=models.IntegerField(default=1000000),
        ),
    ]
