# Generated by Django 4.2.2 on 2023-06-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_cars_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='cost',
            field=models.TextField(default='1000000'),
        ),
    ]
